version: "3.9"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      # args need to be passed decides whether nodemon(dev dependencies) needs to install (here in dev needs to be)
      args: ["NODE_ENV=development"]
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=admin
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
    command: npm run dev
